import { useState } from 'react'
import { Upload, AlertCircle, CheckCircle2 } from 'lucide-react'
import { useInventoryStore } from '../../stores/useInventoryStore'
import { toast } from '../../stores/useToastStore'
import type { Container } from '../../types'

interface ImportModalProps {
  onClose: () => void
  containers: Container[]
}

interface ImportItem {
  name: string
  quantity: number
  unit_value_gp: number | null
  game_date: string
  container_id: string | null
  notes: string
}

export function ImportModal({ onClose, containers }: ImportModalProps) {
  const { importItems } = useInventoryStore()
  const [jsonText, setJsonText] = useState('')
  const [parsed, setParsed] = useState<ImportItem[] | null>(null)
  const [error, setError] = useState<string | null>(null)
  const [importing, setImporting] = useState(false)

  function handleParse() {
    setError(null)
    setParsed(null)
    try {
      const data = JSON.parse(jsonText)
      if (!Array.isArray(data)) {
        setError('Expected a JSON array')
        return
      }
      if (data.length === 0) {
        setError('Array is empty')
        return
      }

      // Validate each item
      const containerIds = new Set(containers.map((c) => c.id))
      const errors: string[] = []
      const items: ImportItem[] = data.map((raw: Record<string, unknown>, i: number) => {
        if (!raw.name || typeof raw.name !== 'string') {
          errors.push(`Item ${i + 1}: missing name`)
        }
        if (raw.container_id && !containerIds.has(raw.container_id as string)) {
          errors.push(`Item ${i + 1}: unknown container "${raw.container_id}"`)
        }
        return {
          name: (raw.name as string) || '',
          quantity: typeof raw.quantity === 'number' ? raw.quantity : 1,
          unit_value_gp: typeof raw.unit_value_gp === 'number' ? raw.unit_value_gp : null,
          game_date: (raw.game_date as string) || '',
          container_id: (raw.container_id as string) || null,
          notes: (raw.notes as string) || '',
        }
      })

      if (errors.length > 0) {
        setError(errors.join('\n'))
        return
      }

      setParsed(items)
    } catch {
      setError('Invalid JSON — check formatting and try again')
    }
  }

  async function handleImport() {
    if (!parsed) return
    setImporting(true)
    try {
      const result = await importItems(parsed)
      toast.success(`Imported ${result.count} items`)
      onClose()
    } catch (e) {
      setError(e instanceof Error ? e.message : 'Import failed')
    } finally {
      setImporting(false)
    }
  }

  function getContainerName(id: string | null): string {
    if (!id) return '—'
    const c = containers.find((c) => c.id === id)
    return c ? c.name : id
  }

  return (
    <div className="fixed inset-0 bg-black/60 flex items-center justify-center z-50 p-4" onClick={onClose}>
      <div className="bg-surface border border-border rounded-xl w-full max-w-3xl max-h-[80vh] flex flex-col" onClick={(e) => e.stopPropagation()}>
        <div className="flex items-center justify-between p-4 border-b border-border">
          <h3 className="font-heading text-lg font-bold text-parchment">Import Items</h3>
          <button onClick={onClose} className="text-parchment-muted hover:text-parchment text-xl">&times;</button>
        </div>

        <div className="p-4 flex-1 overflow-y-auto space-y-4">
          {!parsed ? (
            <>
              <p className="text-sm text-parchment-dim">
                Paste the JSON array generated by your AI conversion tool.
              </p>
              <textarea
                className="input-themed w-full h-48 font-mono text-xs"
                placeholder='[{"name": "Longsword", "quantity": 1, ...}]'
                value={jsonText}
                onChange={(e) => setJsonText(e.target.value)}
              />
              {error && (
                <div className="flex items-start gap-2 text-red-400 text-sm bg-red-400/10 rounded-lg p-3">
                  <AlertCircle className="w-4 h-4 mt-0.5 shrink-0" />
                  <pre className="whitespace-pre-wrap">{error}</pre>
                </div>
              )}
              <button
                onClick={handleParse}
                disabled={!jsonText.trim()}
                className="flex items-center gap-2 px-4 py-2 bg-gold text-base font-heading font-semibold rounded-lg hover:bg-gold-bright text-sm transition-colors disabled:opacity-50"
              >
                Preview
              </button>
            </>
          ) : (
            <>
              <div className="flex items-center gap-2 text-emerald text-sm">
                <CheckCircle2 className="w-4 h-4" />
                {parsed.length} items ready to import
              </div>

              {error && (
                <div className="flex items-start gap-2 text-red-400 text-sm bg-red-400/10 rounded-lg p-3">
                  <AlertCircle className="w-4 h-4 mt-0.5 shrink-0" />
                  <span>{error}</span>
                </div>
              )}

              <div className="overflow-x-auto border border-border rounded-lg">
                <table className="w-full text-sm">
                  <thead>
                    <tr className="bg-card-hover text-parchment-dim">
                      <th className="text-left p-2">Name</th>
                      <th className="text-right p-2">Qty</th>
                      <th className="text-right p-2">Value (gp)</th>
                      <th className="text-left p-2">Container</th>
                      <th className="text-left p-2">Date</th>
                      <th className="text-left p-2">Notes</th>
                    </tr>
                  </thead>
                  <tbody>
                    {parsed.map((item, i) => (
                      <tr key={i} className="border-t border-border">
                        <td className="p-2 text-parchment">{item.name}</td>
                        <td className="p-2 text-right text-parchment-dim">{item.quantity}</td>
                        <td className="p-2 text-right text-gold">{item.unit_value_gp ?? '—'}</td>
                        <td className="p-2 text-parchment-dim">{getContainerName(item.container_id)}</td>
                        <td className="p-2 text-parchment-dim">{item.game_date || '—'}</td>
                        <td className="p-2 text-parchment-dim truncate max-w-[150px]">{item.notes || '—'}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>

              <div className="flex gap-2">
                <button
                  onClick={() => { setParsed(null); setError(null) }}
                  className="px-4 py-2 bg-surface text-parchment-dim border border-border font-heading font-semibold rounded-lg hover:bg-card-hover text-sm transition-colors"
                >
                  Back
                </button>
                <button
                  onClick={handleImport}
                  disabled={importing}
                  className="flex items-center gap-2 px-4 py-2 bg-gold text-base font-heading font-semibold rounded-lg hover:bg-gold-bright text-sm transition-colors disabled:opacity-50"
                >
                  <Upload className="w-4 h-4" />
                  {importing ? 'Importing...' : `Import ${parsed.length} Items`}
                </button>
              </div>
            </>
          )}
        </div>
      </div>
    </div>
  )
}
